from django.urls import path
from .views import (
    nudge_settings,
    gmail_status,
    gmail_oauth_start,
    gmail_oauth_callback,
    gmail_disconnect,
    slack_actions,
    slack_disconnect,
    slack_oauth_callback,
    slack_oauth_start,
    slack_status,
    slack_test_message,
    slack_users_search,
    slack_users_import,
    slack_users_sync,
    notification_list,
    notification_unread_count,
    notification_mark_read,
    notification_mark_all_read,
    calendar_status,
    calendar_oauth_start,
    calendar_oauth_callback,
    calendar_disconnect,
)

urlpatterns = [
    path('nudge-settings/',        nudge_settings,       name='nudge-settings'),
    path('gmail/status/',          gmail_status,         name='gmail-status'),
    path('gmail/oauth/start/',     gmail_oauth_start,    name='gmail-oauth-start'),
    path('gmail/oauth/callback/',  gmail_oauth_callback, name='gmail-oauth-callback'),
    path('gmail/disconnect/',      gmail_disconnect,     name='gmail-disconnect'),
    path('slack/actions/',         slack_actions,         name='slack-actions'),
    path('slack/disconnect/',      slack_disconnect,      name='slack-disconnect'),
    path('slack/oauth/start/',     slack_oauth_start,     name='slack-oauth-start'),
    path('slack/oauth/callback/',  slack_oauth_callback,  name='slack-oauth-callback'),
    path('slack/status/',          slack_status,          name='slack-status'),
    path('slack/test-message/',    slack_test_message,    name='slack-test-message'),
    path('slack/users/',           slack_users_search,    name='slack-users-search'),
    path('slack/users/import/',    slack_users_import,    name='slack-users-import'),
    path('slack/users/sync/',      slack_users_sync,      name='slack-users-sync'),
    path('notifications/',                    notification_list,          name='notification-list'),
    path('notifications/unread-count/',       notification_unread_count,  name='notification-unread-count'),
    path('notifications/mark-all-read/',      notification_mark_all_read, name='notification-mark-all-read'),
    path('notifications/<uuid:pk>/read/',     notification_mark_read,     name='notification-mark-read'),
    path('calendar/status/',                  calendar_status,            name='calendar-status'),
    path('calendar/oauth/start/',             calendar_oauth_start,       name='calendar-oauth-start'),
    path('calendar/oauth/callback/',          calendar_oauth_callback,    name='calendar-oauth-callback'),
    path('calendar/disconnect/',              calendar_disconnect,        name='calendar-disconnect'),
]
