# Generated by Django 6.0.4 on 2026-05-02 20:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commitments', '0002_commitmenttag_commitment_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NudgeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nudged_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(blank=True, max_length=64)),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nudges', to='commitments.commitment')),
            ],
            options={
                'db_table': 'notifications_nudgelog',
                'ordering': ['-nudged_at'],
            },
        ),
    ]
