# Generated by Django 6.0.4 on 2026-05-23 13:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_person_email_nullable'),
        ('commitments', '0005_commitmentevent'),
        ('notifications', '0004_gmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('slack_reply', 'Slack Reply'), ('gmail_reply', 'Gmail Reply')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commitment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='commitments.commitment')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_app_notifications', to='accounts.organisation')),
            ],
            options={
                'db_table': 'notifications_inappnotification',
                'ordering': ['-created_at'],
            },
        ),
    ]
