# Generated by Django 6.0.4 on 2026-05-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_add_inappnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='nudgelog',
            name='last_reply_message_id',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
