# Generated by Django 6.0.4 on 2026-05-24 06:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_person_email_nullable'),
        ('meetings', '0006_meeting_source_file'),
        ('notifications', '0006_nudgelog_last_reply_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('calendar_email', models.EmailField(blank=True, max_length=254)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('transcripts_detected', models.BooleanField(blank=True, null=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_connection', to='accounts.organisation')),
            ],
            options={
                'db_table': 'notifications_calendarconnection',
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_event_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('meet_link', models.URLField(blank=True)),
                ('meet_code', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fetching', 'Fetching transcript'), ('processing', 'Processing'), ('done', 'Done'), ('no_transcript', 'No transcript found'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('drive_file_id', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_event', to='meetings.meeting')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='accounts.organisation')),
            ],
            options={
                'db_table': 'notifications_calendarevent',
                'ordering': ['-starts_at'],
                'unique_together': {('organisation', 'google_event_id')},
            },
        ),
    ]
