# Generated by Django 6.0.4 on 2026-05-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_meetingmanager'),
        ('notifications', '0010_inappnotification_owner_update'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='zoomrecording',
            name='unique_zoom_recording_per_org',
        ),
        migrations.AlterUniqueTogether(
            name='zoomrecording',
            unique_together={('organisation', 'zoom_meeting_uuid')},
        ),
    ]
