# Generated by Django 6.0.4 on 2026-05-25 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_remove_zoomrecording_unique_zoom_recording_per_org_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inappnotification',
            name='recipient_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inappnotification',
            name='notification_type',
            field=models.CharField(choices=[('slack_reply', 'Slack Reply'), ('gmail_reply', 'Gmail Reply'), ('meeting_ready', 'Meeting Ready'), ('meeting_failed', 'Meeting Failed'), ('owner_update', 'Owner Update'), ('commitment_closed', 'Commitment Closed')], max_length=20),
        ),
    ]
