# Generated by Django 6.0.4 on 2026-05-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_inappnotification_recipient_user_and_commitment_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inappnotification',
            name='notification_type',
            field=models.CharField(choices=[('slack_reply', 'Slack Reply'), ('gmail_reply', 'Gmail Reply'), ('meeting_ready', 'Meeting Ready'), ('meeting_failed', 'Meeting Failed'), ('owner_update', 'Owner Update'), ('commitment_closed', 'Commitment Closed'), ('delegation_invite', 'Delegation Invite')], max_length=20),
        ),
    ]
