# Generated by Django 6.0.4 on 2026-05-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_inappnotification_delegation_invite_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='nudgelog',
            name='slack_message_ts',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
