# Generated by Django 6.0.4 on 2026-05-01 02:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_text', models.TextField()),
                ('normalised_text', models.TextField()),
                ('commit_type', models.CharField(choices=[('explicit', 'Explicit')], default='explicit', max_length=20)),
                ('confidence', models.FloatField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('deadline_inferred', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('transcript', 'Extracted from transcript'), ('import', 'Imported from prior tracker')], default='transcript', max_length=20)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('active', 'Active'), ('at_risk', 'At Risk'), ('escalated', 'Escalated'), ('delivered', 'Delivered'), ('deferred', 'Deferred'), ('cancelled', 'Cancelled')], default='pending_review', max_length=20)),
                ('risk_score', models.FloatField(default=0.0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolution_source', models.TextField(blank=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='meetings.meeting')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='accounts.organisation')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_commitments', to='accounts.person')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_commitments', to='accounts.person')),
            ],
            options={
                'db_table': 'commitments_commitment',
                'ordering': ['deadline', '-risk_score'],
            },
        ),
        migrations.CreateModel(
            name='EscalationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('slack', 'Slack'), ('email', 'Email'), ('manual', 'Manual (in-app)'), ('auto', 'Automatic (risk score)')], max_length=20)),
                ('message_sent', models.TextField(blank=True)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('responded', 'Owner responded'), ('resolved', 'Commitment resolved'), ('escalated', 'Further escalated')], default='pending', max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='commitments.commitment')),
                ('escalated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations_sent', to='accounts.person')),
                ('escalated_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations_received', to='accounts.person')),
            ],
            options={
                'db_table': 'commitments_escalationevent',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('confirmed', 'Confirmed — real commitment'), ('rejected', 'Rejected — not a commitment'), ('wrong_owner', 'Wrong owner attributed'), ('wrong_date', 'Deadline was wrong')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('from_import', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='commitments.commitment')),
                ('given_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.person')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organisation')),
            ],
            options={
                'db_table': 'commitments_extractionfeedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='commitment',
            index=models.Index(fields=['organisation', 'status'], name='commitments_organis_13ba1e_idx'),
        ),
        migrations.AddIndex(
            model_name='commitment',
            index=models.Index(fields=['organisation', 'deadline'], name='commitments_organis_c37e30_idx'),
        ),
        migrations.AddIndex(
            model_name='commitment',
            index=models.Index(fields=['owner', 'deadline'], name='commitments_owner_i_b361f2_idx'),
        ),
        migrations.AddIndex(
            model_name='commitment',
            index=models.Index(fields=['organisation', 'risk_score'], name='commitments_organis_fc2ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='commitment',
            index=models.Index(fields=['meeting'], name='commitments_meeting_739954_idx'),
        ),
        migrations.AddIndex(
            model_name='commitment',
            index=models.Index(fields=['organisation', 'source'], name='commitments_organis_6cb673_idx'),
        ),
    ]
