# Generated by Django 6.0.4 on 2026-05-01 12:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_person_first_seen_at_person_meeting_count_and_more'),
        ('commitments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitmentTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitment_tags', to='accounts.organisation')),
            ],
            options={
                'db_table': 'commitments_commitmenttag',
            },
        ),
        migrations.AddField(
            model_name='commitment',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='commitments', to='commitments.commitmenttag'),
        ),
        migrations.AddIndex(
            model_name='commitmenttag',
            index=models.Index(fields=['organisation', 'label'], name='commitments_organis_a8e8e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commitmenttag',
            unique_together={('organisation', 'label')},
        ),
    ]
