# Generated by Django 6.0.4 on 2026-05-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organisation_plan_user_is_org_admin_invitation'),
        ('commitments', '0002_commitmenttag_commitment_tags_and_more'),
        ('meetings', '0002_meetingtopic_meeting_meeting_type_meeting_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='priority',
            field=models.CharField(choices=[('high', 'High (P1)'), ('medium', 'Medium (P2)'), ('low', 'Low (P3)')], default='medium', max_length=10),
        ),
        migrations.AddIndex(
            model_name='commitment',
            index=models.Index(fields=['organisation', 'priority'], name='commitments_organis_b11b78_idx'),
        ),
    ]
