# Generated by Django 6.0.4 on 2026-05-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_meetingmanager'),
        ('commitments', '0005_commitmentevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitmenttag',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commitmenttag',
            name='ai_summary_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commitmenttag',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commitmenttag',
            name='is_initiative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='commitmenttag',
            index=models.Index(fields=['organisation', 'is_initiative'], name='commitments_organis_f00814_idx'),
        ),
    ]
