# Generated by Django 6.0.4 on 2026-05-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='first_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='meeting_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['organisation', 'first_seen_at'], name='accounts_pe_organis_a416fc_idx'),
        ),
    ]
