# Generated by Django 6.0.4 on 2026-05-02 20:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_person_first_seen_at_person_meeting_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='plan',
            field=models.CharField(choices=[('individual', 'Individual'), ('team', 'Team')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_org_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.organisation')),
            ],
            options={
                'db_table': 'accounts_invitation',
                'unique_together': {('organisation', 'email')},
            },
        ),
    ]
