# Generated by Django 6.0.4 on 2026-05-22 00:52

from django.db import migrations, models


def blank_to_null(apps, schema_editor):
    Person = apps.get_model('accounts', 'Person')
    Person.objects.filter(email='').update(email=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organisation_plan_user_is_org_admin_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.RunPython(blank_to_null, migrations.RunPython.noop),
    ]
