# Generated by Django 6.0.4 on 2026-05-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_terms_accepted_at_emailotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='terms_accepted_at',
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('email_verification', 'Email Verification'), ('password_reset', 'Password Reset')], max_length=20),
        ),
    ]
