# Generated by Django 6.0.4 on 2026-05-01 02:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('platform', models.CharField(choices=[('zoom', 'Zoom'), ('upload', 'Manual Upload'), ('import', 'Prior Commitments Import')], default='upload', max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('raw_transcript', models.TextField(blank=True)),
                ('word_count', models.IntegerField(default=0)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('external_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='accounts.organisation')),
            ],
            options={
                'db_table': 'meetings_meeting',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_label', models.CharField(blank=True, max_length=50)),
                ('confirmed', models.BooleanField(default=False)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.person')),
            ],
            options={
                'db_table': 'meetings_meetingparticipant',
                'unique_together': {('meeting', 'person')},
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(related_name='meetings', through='meetings.MeetingParticipant', to='accounts.person'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['organisation', 'occurred_at'], name='meetings_me_organis_14bbf2_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['organisation', 'processing_status'], name='meetings_me_organis_317c28_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['organisation', 'platform'], name='meetings_me_organis_2bfe4c_idx'),
        ),
    ]
