# Generated by Django 6.0.4 on 2026-05-01 12:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_person_first_seen_at_person_meeting_count_and_more'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('confidence', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'meetings_meetingtopic',
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(blank=True, choices=[('leadership', 'Leadership / Exec'), ('one_on_one', '1:1'), ('team', 'Team standup / sync'), ('project', 'Project / workstream'), ('board', 'Board / governance'), ('external', 'External / client'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='meeting',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['organisation', 'meeting_type'], name='meetings_me_organis_6055dd_idx'),
        ),
        migrations.AddField(
            model_name='meetingtopic',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='meetingtopic',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='accounts.organisation'),
        ),
        migrations.AddIndex(
            model_name='meetingtopic',
            index=models.Index(fields=['organisation', 'label'], name='meetings_me_organis_a546d3_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingtopic',
            index=models.Index(fields=['meeting'], name='meetings_me_meeting_325ebf_idx'),
        ),
    ]
