# Generated by Django 6.0.4 on 2026-05-22 03:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_add_pipelinestatus_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='processing_status',
            field=models.CharField(choices=[('pending_participants', 'Awaiting Participant Validation'), ('pending', 'Pending'), ('processing', 'Processing'), ('pending_clarification', 'Awaiting Clarification'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=25),
        ),
        migrations.CreateModel(
            name='MeetingClarification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('context', models.TextField(blank=True)),
                ('answer', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarifications', to='meetings.meeting')),
            ],
            options={
                'db_table': 'meetings_meetingclarification',
                'ordering': ['order'],
            },
        ),
    ]
