import { Commitment } from '../types';

export const MOCK_COMMITMENTS: Commitment[] = [
  {
    id: "1",
    title: "Q2 board deck — pricing section with EMEA scenarios",
    owner: "Sarah K.",
    ownerRole: "CFO",
    deadline: "2026-04-30",
    sourceMeeting: "Q2 Strategic Planning",
    meetingDate: "2026-04-22",
    status: "overdue",
    priority: "High",
    riskScore: 0.94,
    tags: ["board-prep", "pricing", "emea"],
    nudgeCount: 3,
    needs_manual_nudge: true,
  },
  {
    id: "2",
    title: "Finalise engineering lead hiring brief for HR review",
    owner: "Tom R.",
    ownerRole: "VP Engineering",
    deadline: "2026-05-22",
    sourceMeeting: "Engineering Sync",
    meetingDate: "2026-05-15",
    status: "at_risk",
    priority: "High",
    riskScore: 0.78,
    tags: ["hiring", "eng-ops"],
    nudgeCount: 1,
    needs_manual_nudge: true,
  },
  {
    id: "3",
    title: "Draft product roadmap v2 with new core logic features",
    owner: "Maya L.",
    ownerRole: "Head of Product",
    deadline: "2026-05-25",
    sourceMeeting: "Product Standup",
    meetingDate: "2026-05-18",
    status: "on_track",
    priority: "Med",
    riskScore: 0.25,
    tags: ["roadmap", "product"],
  },
  {
    id: "4",
    title: "Update Q2 revenue forecast with revised EMEA figures",
    owner: "Sarah K.",
    ownerRole: "CFO",
    deadline: "2026-05-20",
    sourceMeeting: "Finance Monthly",
    meetingDate: "2026-05-10",
    status: "overdue",
    priority: "High",
    riskScore: 0.88,
    tags: ["finance", "emea"],
    nudgeCount: 2,
  },
  {
    id: "5",
    title: "Review customer support SLA reports for April",
    owner: "David B.",
    ownerRole: "COO",
    deadline: "2026-05-28",
    sourceMeeting: "Operations Sync",
    meetingDate: "2026-05-15",
    status: "on_track",
    priority: "Low",
    riskScore: 0.15,
    tags: ["ops", "customer-success"],
  },
  {
    id: "6",
    title: "Q1 board minutes approved and filed",
    owner: "Sarah K.",
    ownerRole: "CFO",
    deadline: "2026-04-15",
    sourceMeeting: "Board Meeting",
    meetingDate: "2026-04-10",
    status: "done",
    priority: "Low",
    riskScore: 0.05,
    tags: ["board-prep", "legal"],
  },
];
