# Generated by Django 6.0.4 on 2026-05-28 10:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_meetingmanager'),
        ('prompts', '0005_seed_initiative_and_autotag_prompts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICallLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_name', models.CharField(db_index=True, max_length=100)),
                ('prompt_version', models.PositiveIntegerField(default=0)),
                ('input_text', models.TextField()),
                ('output_text', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField()),
                ('success', models.BooleanField()),
                ('error', models.TextField(blank=True)),
                ('meeting_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('commitment_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('tag_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_call_logs', to='accounts.organisation')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prompts_aicalllog',
                'ordering': ['-created_at'],
            },
        ),
    ]
